import { test, expect } from '@playwright/test';

test('advance_report', async ({ page }) => {
  await page.getByRole('button', { name: ' Home' }).click();
  await page.getByRole('link', { name: 'Faculty Login' }).click();
  await page.goto('https://cht14v4.linways.com/ams/faculty/login');
  await page.getByRole('textbox', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Login' }).fill('admissiontest');
  await page.getByRole('textbox', { name: 'Login' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('');
  await page.getByRole('textbox', { name: 'Login' }).dblclick();
  await page.getByRole('textbox', { name: 'Login' }).fill('erpadmin');
  await page.getByRole('textbox', { name: 'Login' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('123');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('link', { name: 'apps' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('menu', { name: 'apps' }).getByText('apartment').click();
  const page1 = await page1Promise;
  await page1.goto('https://cht14v4.linways.com/hostel/dashboard');
  await page1.getByRole('button', { name: ' Back' }).click();
  await page1.getByRole('button', { name: ' Home' }).click();
  await page1.getByRole('link', { name: 'Faculty Login' }).click();
  await page1.getByRole('listitem').filter({ hasText: 'appsRolesFaculty' }).click();
  await page1.getByRole('link', { name: 'apps' }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('menu', { name: 'apps' }).getByText('apartment').click();
  const page2 = await page2Promise;
  await page2.getByRole('link', { name: 'Reports ' }).click();
  await page2.getByRole('link', { name: 'Attendance Report' }).click();
  await page2.locator('input[type="search"]').click();
  await page2.getByRole('textbox').first().click();
  await page2.getByLabel('Month').first().selectOption('0');
  await page2.getByLabel('January 1,').click();
  await page2.locator('#messExpectedFromDate').fill('2026-01-01');
  await page2.locator('input[type="search"]').click();
  await page2.locator('input[type="search"]').click();
  await page2.locator('input[type="search"]').click();
  await page2.getByRole('button', { name: ' Search' }).click();
});